name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main        # ¿en qué rama quieres que se active?

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Deploy to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EJEMPLO1_98008 }}"
        # ¿qué secret usamos aquí?